[queries]
[queries.join1]
type="join"
count=true
[queries.join1.A_scan]
type="scan"
table="A"
inputs=["filter_col"]
projections=["filter_col"]
[[queries.join1.A_scan.filters]]
col="filter_col"
expr = "between"
left_closed = true
right_closed = true
vals=["1", "31"] # Updates will set the embedding value to 0.


[queries.join1.B_scan]
type="scan"
table="B"
inputs=[]
projections=[]