# Only with star schemas.
workload_title = "synthetic_workload"
input_folder = "synthetic_workload"
data_folder = "synthetic_workload_data"
central_table = "A"
log_vec_size = 11
log_block_size = 18
log_mem_space = 34 # 16GB
log_disk_space = 36 # 64GB
reload = false # For reloading data.
gen_costs = false # For generating optimization costs.
rebuild = false # For rebuilding mat_views, indexes or smartids.
budget=64 # In multiples of 64MB from 0 to 64.
embedding_size=16

[tables]
[tables.A]
datafile="A.csv"
primary=["id"]
[[tables.A.col]]
name="id"
type="bigint"
[[tables.A.col]]
name="filter_col"
type="int"


[tables.B]
datafile="B.csv"
primary=["id"]
to_many=true
[[tables.B.col]]
name="id"
type="int"
[[tables.B.col]]
name="fk"
type="bigint"
foreign="id"
