[queries]
[queries.join1]
type="join"
count=true
[queries.join1.A_scan]
type="scan"
table="A"
inputs=["filter_col"]
projections=["filter_col"]
[[queries.join1.title_scan.filters]]
col="filter_col"
expr = "eq"
vals=["1"] # Updates will set the embedding value to 0.


[queries.join1.movie_info_idx_scan]
type="scan"
table="movie_info_idx"
inputs=["movie_id", "info_type_id"]
projections=["movie_id", "info_type_id"]

[[queries.join1.movie_info_idx_scan.filters]]
col="info_type_id"
expr = "eq"
val = "112"
