# Assume all queries are scans or simple joins.
[queries]
[queries.scan1]
type="scan"
table="central_table"
projections=["id1", "id2", "int64_col"]
[[queries.scan1.filters]]
col="int64_col"
op = "lt"
vals=["?"]




[queries.scan2]
type="scan"
table="dimension_table1"
projections=["id", "fk", "int16_col", "int32_col"]
[[queries.scan2.filters]]
col="int16_col"
op="ge"
vals=["?"]
[[queries.scan2.filters]]
col="int32_col"
op="between"
vals=["5", "8"]


[queries.scan3]
type="scan"
table="dimension_table2"
projections=["id", "fk", "text_col", "date_col"]
[[queries.scan3.filters]]
col="text_col"
op="eq"
vals=['?']
[[queries.scan3.filters]]
col="date_col"
op="between"
vals=["2000-01-01", "2010-01-01"]


[queries.scan4]
type="scan"
table="dimension_table3"
projections=["id", "fk", "float32_col", "float64_col"]
[[queries.scan4.filters]]
col="float32_col"
op="ge"
vals=['?']
[[queries.scan4.filters]]
col="float64_col"
op="between"
vals=['?']
