[queries]
[queries.query1]
type="join"
count=true

[queries.query1.scan1]
type="scan"
table="central_table"
inputs=["int32_col"] # Only read and project join keys if wanted in the output
projections=["int32_col"]
[[queries.query1.scan1.filters]]
col="int32_col"
expr = "le"
val = "256"

[queries.query1.scan4]
type="scan"
table="dimension_table3"
inputs=["int32_col"]
projections=["int32_col"]
# [[queries.query1.scan4.filters]]
# col="int32_col"
# expr = "between"
# vals = ["0", "1024"]

[queries.query1.scan5]
type="scan"
table="dimension_table4"
inputs=["char_col"]
projections=["char_col"]
