# Only with star schemas.
workload_title = "sample_workload"
input_folder = "sample_workload"
data_folder = "sample_workload_data"
central_table = "central_table"
log_vec_size = 6 # Minimum is 6.
log_block_size = 7
log_mem_space = 20 # 1MB
log_disk_space = 35 # 32GB
reload = false

[tables]
[tables.central_table]
datafile="central_table.tbl"
primary=["id"]
[[tables.central_table.col]]
name="id"
type="bigint"
[[tables.central_table.col]]
name="id1"
type="bigint"
[[tables.central_table.col]]
name="id2"
type="bigint"
[[tables.central_table.col]]
name="int64_col"
type="bigint"



[tables.dimension_table1]
datafile="dimension_table1.tbl"
one_to_many=false
primary=["id"]
[[tables.dimension_table1.col]]
name="id"
type="bigint"
[[tables.dimension_table1.col]]
name="fk"
type="bigint"
foreign="id1"
[[tables.dimension_table1.col]]
name="int32_col"
type="int"
[[tables.dimension_table1.col]]
name="int16_col"
type="smallint"


[tables.dimension_table2]
datafile="dimension_table2.tbl"
primary=["id"]
to_many=false
[[tables.dimension_table2.col]]
name="id"
type="bigint"
[[tables.dimension_table2.col]]
name="fk"
type="bigint"
foreign="id2"
[[tables.dimension_table2.col]]
name="text_col"
type="int"
dict_encode=true
[[tables.dimension_table2.col]]
name="date_col"
type="date"


[tables.dimension_table3]
datafile="dimension_table3.tbl"
primary=["id"]
to_many=true
[[tables.dimension_table3.col]]
name="id"
type="bigint"
[[tables.dimension_table3.col]]
name="fk"
type="bigint"
foreign="id"
[[tables.dimension_table3.col]]
name="float32_col"
type="float"
[[tables.dimension_table3.col]]
name="float64_col"
type="double"


[tables.dimension_table4]
datafile="dimension_table4.tbl"
primary=["id"]
to_many=true
[[tables.dimension_table4.col]]
name="id"
type="bigint"
[[tables.dimension_table4.col]]
name="fk"
type="bigint"
foreign="id"
[[tables.dimension_table4.col]]
name="int8_col"
type="tinyint"
[[tables.dimension_table4.col]]
name="char_col"
type="char"

