# Only with star schemas.
workload_title = "sample_workload"
input_folder = "sample_workload"
data_folder = "sample_workload_data"
central_table = "central_table"
log_vec_size = 6 # Minimum is 6.
log_block_size = 7
log_mem_space = 30 # 1GB
log_disk_space = 35 # 32GB
reload = false # For reloading data.
gen_costs = false # For generating optimization costs.
rebuild = false # For rebuilding mat_views, indexes or smartids.
budget=2 # In multiples of 64MB from 0 to 64.
embedding_size=8


[tables]
[tables.central_table]
datafile="central_table.tbl"
primary=["id"]
[[tables.central_table.col]]
name="id"
type="int"
[[tables.central_table.col]]
name="id1"
type="bigint"
[[tables.central_table.col]]
name="id2"
type="bigint"
[[tables.central_table.col]]
name="int32_col"
type="int"



[tables.dimension_table3]
datafile="dimension_table3.tbl"
primary=["id"]
to_many=true
[[tables.dimension_table3.col]]
name="id"
type="int"
[[tables.dimension_table3.col]]
name="fk"
type="int"
foreign="id"
[[tables.dimension_table3.col]]
name="int32_col"
type="int"
[[tables.dimension_table3.col]]
name="float32_col"
type="float"
[[tables.dimension_table3.col]]
name="float64_col"
type="double"


[tables.dimension_table4]
datafile="dimension_table4.tbl"
primary=["id"]
to_many=true
[[tables.dimension_table4.col]]
name="id"
type="int"
[[tables.dimension_table4.col]]
name="fk"
type="int"
foreign="id"
[[tables.dimension_table4.col]]
name="int8_col"
type="tinyint"
[[tables.dimension_table4.col]]
name="char_col"
type="char"

